cache: apt
sudo: required
dist: trusty
matrix:
  include:
    - language: node_js
      node_js:
        - '16.13'
      before_install:
        - npm install npm@8.1 -g
      install:
        - npm ci --ignore-engines
      script:
        - npm run lint
        - npm test
      after_script:
        - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]] || [[ "$TRAVIS_BRANCH" == "master"
          ]]; then npm run upload:coverage; else echo "coverage upload is not required";
          fi;
